export const LoaderIPLConfig = {
    cayoIsland: {
        interiorID: undefined,
        interiorCords: undefined,
        ipls: [
            'h4_islandairstrip',
            'h4_islandairstrip_props',
            'h4_islandx_mansion',
            'h4_islandx_mansion_props',
            'h4_islandx_props',
            'h4_islandxdock',
            'h4_islandxdock_props',
            'h4_islandxdock_props_2',
            'h4_islandxtower',
            'h4_islandx_maindock',
            'h4_islandx_maindock_props',
            'h4_islandx_maindock_props_2',
            'h4_IslandX_Mansion_Vault',
            'h4_islandairstrip_propsb',
            'h4_beach',
            'h4_beach_props',
            'h4_beach_bar_props',
            'h4_islandx_barrack_props',
            'h4_islandx_checkpoint',
            'h4_islandx_checkpoint_props',
            'h4_islandx_Mansion_Office',
            'h4_islandx_Mansion_LockUp_01',
            'h4_islandx_Mansion_LockUp_02',
            'h4_islandx_Mansion_LockUp_03',
            'h4_islandairstrip_hangar_props',
            'h4_IslandX_Mansion_B',
            'h4_islandairstrip_doorsclosed',
            'h4_Underwater_Gate_Closed',
            'h4_mansion_gate_closed',
            'h4_aa_guns',
            'h4_IslandX_Mansion_GuardFence',
            'h4_IslandX_Mansion_Entrance_Fence',
            'h4_IslandX_Mansion_B_Side_Fence',
            'h4_IslandX_Mansion_Lights',
            'h4_islandxcanal_props',
            'h4_beach_props_party',
            'h4_islandX_Terrain_props_06_a',
            'h4_islandX_Terrain_props_06_b',
            'h4_islandX_Terrain_props_06_c',
            'h4_islandX_Terrain_props_05_a',
            'h4_islandX_Terrain_props_05_b',
            'h4_islandX_Terrain_props_05_c',
            'h4_islandX_Terrain_props_05_d',
            'h4_islandX_Terrain_props_05_e',
            'h4_islandX_Terrain_props_05_f',
            'H4_islandx_terrain_01',
            'H4_islandx_terrain_02',
            'H4_islandx_terrain_03',
            'H4_islandx_terrain_04',
            'H4_islandx_terrain_05',
            'H4_islandx_terrain_06',
            'h4_ne_ipl_00',
            'h4_ne_ipl_01',
            'h4_ne_ipl_02',
            'h4_ne_ipl_03',
            'h4_ne_ipl_04',
            'h4_ne_ipl_05',
            'h4_ne_ipl_06',
            'h4_ne_ipl_07',
            'h4_ne_ipl_08',
            'h4_ne_ipl_09',
            'h4_nw_ipl_00',
            'h4_nw_ipl_01',
            'h4_nw_ipl_02',
            'h4_nw_ipl_03',
            'h4_nw_ipl_04',
            'h4_nw_ipl_05',
            'h4_nw_ipl_06',
            'h4_nw_ipl_07',
            'h4_nw_ipl_08',
            'h4_nw_ipl_09',
            'h4_se_ipl_00',
            'h4_se_ipl_01',
            'h4_se_ipl_02',
            'h4_se_ipl_03',
            'h4_se_ipl_04',
            'h4_se_ipl_05',
            'h4_se_ipl_06',
            'h4_se_ipl_07',
            'h4_se_ipl_08',
            'h4_se_ipl_09',
            'h4_sw_ipl_00',
            'h4_sw_ipl_01',
            'h4_sw_ipl_02',
            'h4_sw_ipl_03',
            'h4_sw_ipl_04',
            'h4_sw_ipl_05',
            'h4_sw_ipl_06',
            'h4_sw_ipl_07',
            'h4_sw_ipl_08',
            'h4_sw_ipl_09',
            'h4_islandx_mansion',
            'h4_islandxtower_veg',
            'h4_islandx_sea_mines',
            'h4_islandx',
            'h4_islandx_barrack_hatch',
            'h4_islandxdock_water_hatch',
            'h4_beach_party',
            'h4_mph4_terrain_01_grass_0',
            'h4_mph4_terrain_01_grass_1',
            'h4_mph4_terrain_02_grass_0',
            'h4_mph4_terrain_02_grass_1',
            'h4_mph4_terrain_02_grass_2',
            'h4_mph4_terrain_02_grass_3',
            'h4_mph4_terrain_04_grass_0',
            'h4_mph4_terrain_04_grass_1',
            'h4_mph4_terrain_04_grass_2',
            'h4_mph4_terrain_04_grass_3',
            'h4_mph4_terrain_05_grass_0',
            'h4_mph4_terrain_06_grass_0',
            'h4_mph4_airstrip_interior_0_airstrip_hanger',
        ],
        entities: [],
    },
    casino: {
        interiorID: undefined,
        interiorCords: { x: 976.636, y: 70.295, z: 115.164 },
        ipls: [
            'vw_casino_main',
            'vw_casino_garage',
            'vw_casino_carpark',
            'vw_casino_penthouse',
            'vw_dlc_casino_door',
            'hei_dlc_casino_door',
            'hei_dlc_windows_casino',
            'hei_dlc_casino_aircon',
        ],
        entities: [
            'Set_Pent_Tint_Shell',
            'Set_Pent_Pattern_01',
            'Set_Pent_Spa_Bar_Open',
            'Set_Pent_Media_Bar_Open',
            'Set_Pent_Dealer',
            'Set_Pent_Arcade_Retro',
            'Set_Pent_Bar_Clutter',
            'Set_Pent_Clutter_01',
            'set_pent_bar_light_01',
            'set_pent_bar_party_0',
        ],
    },
    simeonDealership: {
        interiorID: undefined,
        interiorCords: { x: -42.950679779052734, y: -1098.60986328125, z: 26.422361373901367 },
        ipls: ['reh_simeonfix'],
        entities: ['csr_beforeMission', 'shutter_opened'],
    },
    mpsecurity: {
        interiorID: undefined,
        interiorCords: { x: -1021.9268798828125, y: -424.1511535644531, z: 72.4611587524414 },
        ipls: [
            'sf_fixeroffice_hw1_08',
            'sf_fixeroffice_kt1_05',
            'sf_fixeroffice_kt1_08',
            'sf_int_placement_sec_interior_1_dlc_studio_sec_milo_',
            'sf_musicrooftop',
            'sf_int_placement_sec_interior_2_dlc_garage_sec_milo_',
            'sf_billboards',
            'sf_fixeroffice_bh1_05',
        ],
        entities: [
            'Entity_Set_Armoury',
            'Entity_Set_Wpaper_1',
            'Entity_Set_Moving',
            'Entity_Set_Tint_AG',
            'Entity_Set_Spare_Seats',
            'Entity_Set_Player_Seats',
            'Entity_Set_M_Golf_Intro',
            'Entity_Set_M_Setup',
            'Entity_Set_M_Nightclub',
            'Entity_Set_M_Yacht',
            'Entity_Set_M_Promoter',
            'Entity_Set_M_Limo_Photo',
            'Entity_Set_M_Limo_Wallet',
            'Entity_Set_M_The_Way',
            'Entity_Set_M_Billionaire',
            'Entity_Set_M_Families',
            'Entity_Set_M_Ballas',
            'Entity_Set_M_Hood',
            'Entity_Set_M_Fire_Booth',
            'Entity_Set_M_50',
            'Entity_Set_M_Taxi',
            'Entity_Set_M_Gone_Golfing',
            'Entity_Set_M_Motel',
            'Entity_Set_M_Construction',
            'Entity_Set_M_Hit_List',
            'Entity_Set_M_Tuner',
            'Entity_Set_M_Attack',
            'Entity_Set_M_Vehicles',
            'Entity_Set_M_Trip_01',
            'Entity_Set_M_Trip_02',
            'Entity_Set_M_Trip_03',
            'Entity_set_disc_01',
            'Entity_Set_Art_2',
        ],
    },
    michaelHouse: {
        interiorID: undefined,
        interiorCords: { x: -810.206298828125, y: 180.18844604492188, z: 72.1531753540039 },
        ipls: [],
        entities: [
            'v_michael_d_items',
            'v_michael_m_items',
            'v_michael_m_items_swap',
            'v_michael_s_items',
            'v_michael_s_items_swap',
            'michael_premier',
            'v_michael_l_items',
            'v_michael_jewelheist',
            'v_michael_fameshame',
            'v_michael_plane_ticket',
            'v_michael_bed_messy',
            'v_michael_bed_tidy',
            'v_michael_book',
        ],
    },
    chopShop: {
        interiorID: 293633,
        interiorCords: undefined,
        ipls: [
            'm23_2_acp_collision_fixes_01',
            'm23_2_acp_collision_fixes_02',
            'm23_2_tug_collision',
            'm23_2_hei_yacht_collision_fixes',
            'm23_2_vinewood_garage',
            'm23_2_cargoship',
            'm23_2_cargoship_bridge',
            'm23_2_lifeguard_access',
        ],
        entities: ['mp2023_02_dlc_int_6_cb'],
    },
    salvage: {
        interiorID: 293377,
        interiorCords: undefined,
        ipls: ['m23_2_sp1_03_reds', 'm23_2_sc1_03_reds', 'm23_2_id2_04_reds', 'm23_2_cs1_05_reds', 'm23_2_cs4_11_reds'],
        entities: [],
    },
    mercenariesDlc: {
        interiorID: undefined,
        interiorCords: undefined,
        ipls: ['m23_1_legacy_fixes'],
        entities: [],
    },
    MercenariesClub: {
        interiorID: 291841,
        interiorCords: undefined,
        ipls: [],
        entities: ['entity_set_no_plus', 'entity_set_plus', 'entity_set_backdrop_frames', 'entity_set_signs'],
    },
    MercenariesLab: {
        interiorID: 292097,
        interiorCords: undefined,
        ipls: [],
        entities: ['entity_set_levers', 'entity_set_crates', 'entity_set_weapons', 'entity_set_lift_lights'],
    },
    TunerGarage: {
        interiorID: 285953,
        interiorCords: undefined,
        ipls: [
            'tr_tuner_shop_burton',
            'tr_tuner_shop_mesa',
            'tr_tuner_shop_mission',
            'tr_tuner_shop_rancho',
            'tr_tuner_shop_strawberry',
        ],
        entities: [
            'entity_set_bedroom',
            'entity_set_bombs',
            'entity_set_car_lift_cutscene',
            'entity_set_car_lift_default',
            'entity_set_car_lift_purchase',
            'entity_set_drive',
            'entity_set_ecu',
            'entity_set_IAA',
            'entity_set_jammers',
            'entity_set_laptop',
            'entity_set_lightbox',
            'entity_set_plate',
            'entity_set_scope',
            'entity_set_style_9',
            'entity_set_thermal',
            'entity_set_tints',
            'entity_set_train',
            'entity_set_virus',
        ],
    },
    DoomsdayFacility: {
        interiorID: 269313,
        interiorCords: undefined,
        ipls: [
            'xm_x17dlc_int_placement_interior_33_x17dlc_int_02_milo_',
            'xm_hatch_01_cutscene', // 1286.924 2846.06 49.39426
            'xm_hatch_02_cutscene', // 18.633 2610.834 86.0
            'xm_hatch_03_cutscene', // 2768.574 3919.924 45.82
            'xm_hatch_04_cutscene', // 3406.90 5504.77 26.28
            'xm_hatch_06_cutscene', // 1.90 6832.18 15.82
            'xm_hatch_07_cutscene', // -2231.53 2418.42 12.18
            'xm_hatch_08_cutscene', // -6.92 3327.0 41.63
            'xm_hatch_09_cutscene', // 2073.62 1748.77 104.51
            'xm_hatch_10_cutscene', // 1874.35 284.34 164.31
            // 'xm_hatch_closed', // Closed hatches (all)
            'xm_siloentranceclosed_x17', // Closed silo: 598.4869 5556.846 716.7615
            'xm_bunkerentrance_door', // Bunker entrance closed door: 2050.85 2950.0 47.75
            'xm_hatches_terrain', // Terrain adjustments for facilities (all) + silo
            'xm_hatches_terrain_lod',
        ],
        entities: [
            'set_int_02_shell',
            'set_int_02_decal_01',
            'set_int_02_decal_02',
            'set_int_02_decal_03',
            'set_int_02_decal_04',
            'set_int_02_decal_05',
            'set_int_02_decal_06',
            'set_int_02_decal_07',
            'set_int_02_decal_08',
            'set_int_02_decal_09',
            'set_int_02_lounge1',
            'set_int_02_lounge2',
            'set_int_02_lounge3',
            'set_int_02_no_sleep',
            'set_int_02_sleep',
            'set_int_02_sleep2',
            'set_int_02_sleep3',
            'set_int_02_security',
            'set_int_02_cannon',
        ],
    },
    DrugWarsGarage: {
        interiorID: 290561,
        interiorCords: undefined,
        ipls: ['xm3_garage_fix'],
        entities: [],
    },
    DrugWarsFreakshop: {
        interiorID: 290817,
        interiorCords: undefined,
        ipls: ['xm3_dlc_int_01_xm3'],
        entities: ['entity_set_roller_door_closed'],
    },
    DrugWarsBoulevardGarage: {
        interiorID: 290561,
        interiorCords: undefined,
        ipls: ['xm3_dlc_int_02_xm3'],
        entities: ['entity_set_numbers_01', 'entity_set_shell_03', 'entity_set_tint_01'],
    },
};








